name: Mirror Repository

on:
  workflow_dispatch: # TODO: remove
  push:
    branches:
      - pipelines  # Change this to your source branch.

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Mirror to Security Repository
        run: |
          TARGET_REPO_NAME="${{ github.repository_owner }}/corvina-k8s-security"
          git clone --bare https://github.com/${{ github.repository }}.git
          cd "$(basename "${{ github.repository }}")"
          git push --mirror "https://github.com/${TARGET_REPO_NAME}.git"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
