name: Mirror Repository

on:
  workflow_dispatch: # TODO: remove
  push:
    branches:
      - pipelines  # Change this to your source branch.

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mirror to Target Repository
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          git push --mirror "git@github.com:basil3366/newrep-security.git"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

